(1,"Cement Mason", "Zoster iridocyclitis","€48,09"),
(2,"Stucco Masond", "Other chronic osteomyelitis, tibia and fibula","€86,13"),
(3,"Carpenterd", "Unsp fracture of third thor vertebra, subs for fx w nonunion","€20,56"),
(2,"Brickmasond", "Other specified injury of blood vessel of unspecified thumb","€133,12"),
(2,"Equipment Operatord", "Stenosis due to genitourinary prosth dev/grft","€86,64"),
(2,"Welderd", "Encntr for gyn exam (general) (routine) w abnormal findings","€78,18"),
(1,"Safety Officerd", "Other obstructive and reflux uropathy","€131,85"),
(1,"Safety Officerd", "Toxic effect of sulfur dioxide, assault, sequela","€74,41"),
(2,"Landscaperd", "Oth athscl nonbiological bypass of the extremities, left leg","€123,62"),
(3,"Painter", "Burn of second degree of left toe(s) (nail), subs encntr","€135,40"),
(1,"Welder", "Mech compl of ocular prosth dev/grft, init","€43,16"),
(2,"Brickmason", "Driver of hv veh inj in clsn w rail trn/veh nontraf, sequela","€43,69"),
(1,"Concrete Finisher", "Athscl nonaut bio bypass of the extrm w rest pain, bi legs","€62,19"),
(2,"HVAC", "Open bite of nose, subsequent encounter","€49,55"),
(3,"Concrete Finisher", "Poisoning by aspirin, assault, initial encounter","€45,63"),
(2,"Pipelayer", "Displ spiral fx shaft of rad, l arm, 7thB","€106,71"),
(2,"Plasterers", "Other mature T/NK-cell lymphomas, spleen","€106,22"),
(2,"HVAC", "Scarlet fever","€140,98"),
(1,"Millwright", "Injury of left iliac vein, subsequent encounter","€54,85"),
(1,"Cement Mason", "Nondisp avulsion fracture of tuberosity of unsp calcaneus","€46,91"),
(2,"Refridgeration", "Bent bone of right radius, init encntr for closed fracture","€147,28"),
(3,"Terrazzo", "Xanthelasma of right eye, unspecified eyelid","€73,48"),
(1,"Electrician", "Oth injury of unsp pulmonary blood vessels, init encntr","€58,23"),
(2,"HVAC", "Unsp injury of superfic palmar arch of right hand, sequela","€65,86"),
(1,"Safety Officer", "Rheumatoid vasculitis with rheumatoid arthritis","€124,60"),
(2,"Equipment Operator", "Oligospermia due to extratesticular causes","€64,23"),
(3,"Millwright", "Other infective bursitis, ankle and foot","€29,50"),
(2,"Electrician", "Connective tiss and disc stenosis of intervertebral foramina","€130,94"),
(2,"Brickmason", "Toxic effect of aflatoxin, undetermined, subs encntr","€84,25"),
(2,"Waterproofer", "Other meniscus derangements, other lateral meniscus","€128,09"),
(1,"Stucco Mason", "Displ commnt fx shaft of l tibia, 7thP","€80,54"),
(1,"Sheet Metal Worker", "Disp fx of nk of scapula, l shldr, subs for fx w delay heal","€134,85"),
(2,"Terrazzo", "Other specified injury of femoral artery, left leg","€138,00"),
(3,"Landscaper", "Strain of musc/tend at lower leg level, right leg, subs","€58,84"),
(1,"Glazier", "Rheumatoid nodule, right knee","€100,09"),
(2,"Concrete Finisher", "Drug/chem diab with mild nonp rtnop with mclr edema, r eye","€103,99"),
(1,"Tile Setter", "Nondisp spiral fracture of shaft of humerus, left arm, init","€117,48"),
(2,"Equipment Operator", "Nondisp fx of base of nk of unsp femr, 7thF","€132,97"),
(3,"Ironworker", "Secondary malignant neoplasm of brain and cerebral meninges","€50,94"),
(2,"Sheet Metal Worker", "High altitude periodic breathing","€39,14"),
(2,"Glazier", "Occ of rail trn/veh inj in collisn/hit by roll stok, subs","€31,06"),
(2,"Linemen", "Babystroller colliding with stationary object, sequela","€100,89"),
(1,"Boilermaker", "Toxic effect of nitrodrv/aminodrv of benzn/homolog, undet","€86,38"),
(1,"Glazier", "Laceration of gallbladder, sequela","€99,91"),
(2,"Landscaper", "Poor urinary stream","€120,62"),
(3,"Concrete Finisher", "Fall from non-moving nonmotorized scooter, sequela","€119,12"),
(1,"Sheet Metal Worker", "Inj intrinsic musc/fasc/tend finger at wrs/hnd lv, subs","€127,86"),
(2,"Painter", "Disp fx of dist pole of navic bone of l wrs, 7thG","€136,73"),
(1,"Pipefitter", "Nondisp intartic fx r calcaneus, subs for fx w nonunion","€143,63"),
(2,"Laborer", "Encounter for prophylactic rabies immune globin","€79,62"),
(3,"Cement Mason", "Unsp fb in esophagus causing compression of trachea, sequela","€119,07"),
(2,"Laborer", "Unsp trochanteric fracture of unsp femur, init for clos fx","€74,78"),
(2,"Tile Setter", "Oth nondisp fx of low end r humer, subs for fx w delay heal","€122,94"),
(2,"Tile Setter", "Displaced transverse fx left acetabulum, init for opn fx","€90,22"),
(1,"Landscaper", "Corrosion of third degree of chin, sequela","€55,25"),
(1,"Equipment Operator", "Nondisp transverse fx unsp patella, 7thP","€42,08"),
(2,"Welder", "Acute embolism and thrombosis of deep vein of r low extrem","€78,85"),
(3,"Ironworker", "Drug-induced cataract, right eye","€75,99"),
(1,"Landscaper", "Unsp physl fx upper end l fibula, subs for fx w routn heal","€25,90"),
(2,"Waterproofer", "Sprain of right sternoclavicular joint","€109,54"),
(1,"Painter", "Minor laceration of superior vena cava, initial encounter","€93,97"),
(2,"Linemen", "Posterior cyclitis, left eye","€27,19"),
(3,"HVAC", "Bipolar disorder, current episode depressed, mild","€20,79"),
(2,"Millwright", "Allergic contact dermatitis due to drugs in contact w skin","€98,09"),
(2,"Refridgeration", "Oth maternal infec/parastc diseases comp preg, first tri","€62,83"),
(2,"Sheet Metal Worker", "Unspecified fracture of lower end of tibia","€134,38"),
(1,"Pipefitter", "Disp fx of dist phalanx of l mid fngr, 7thK","€31,65"),
(1,"Plumber", "Burn of third degree of right forearm, initial encounter","€145,45"),
(2,"Painter", "Bent bone of unsp ulna, subs for clos fx w routn heal","€103,11"),
(3,"Terrazzo", "Atrioventricular septal defect","€130,39"),
(1,"Welder", "Corrosion of first deg mult sites of right ank/ft, init","€132,60"),
(2,"Plasterers", "Malar fracture, right side, 7thG","€137,58"),
(1,"Landscaper", "Wrist or foot drop (acquired)","€71,45"),
(2,"Refridgeration", "Sltr-haris Type I physl fx low end humer, l arm, 7thK","€44,00"),
(3,"Ironworker", "Toxic effect of cobra venom","€63,33"),
(2,"Sheet Metal Worker", "Villonodular synovitis (pigmented), left wrist","€78,87"),
(2,"Pipefitter", "Subluxation of unspecified cervical vertebrae, init encntr","€99,35"),
(2,"Safety Officer", "Crushing injury of right great toe","€56,49"),
(1,"Safety Officer", "Matern care for viable fetus in abd preg, second tri, fts2","€42,22"),
(1,"Boilermaker", "36 weeks gestation of pregnancy","€38,14"),
(2,"Electrician", "Disp fx of l ulna styloid pro, 7thM","€135,16"),
(3,"Waterproofer", "Corros unsp degree of head, face, and neck, unsp site, sqla","€134,04"),
(1,"Pipefitter", "Occ of anml-drn vehicle inj in clsn w statnry object, sqla","€133,26"),
(2,"Concrete Finisher", "Nondisp fx of posterior process of left talus, sequela","€84,03"),
(1,"Pipefitter", "Syphilis complicating pregnancy","€88,24"),
(2,"Landscaper", "Burn of second degree of unspecified axilla, sequela","€82,56"),
(3,"Concrete Finisher", "Struck by crocodile, sequela","€98,96"),
(2,"Ironworker", "Rider of nonpowered watercraft struck by powered watercraft","€89,74"),
(2,"Equipment Operator", "Sltr-haris Type I physeal fx lower end of left tibia","€135,46"),
(2,"Pipelayer", "Displacement of ventricular intracranial shunt, sequela","€135,30"),
(1,"Brickmason", "Unsp fracture of the lower end of left radius, init","€38,79"),
(1,"HVAC", "Laceration of kidney, unspecified degree","€131,03"),
(2,"Linemen", "Stress fracture, right humerus, subs for fx w delay heal","€44,86"),
(3,"Landscaper", "Corros 1st deg of unsp site left lower limb, ex ank/ft, sqla","€131,68"),
(1,"Waterproofer", "Other specified peripheral vascular diseases","€86,40"),
(2,"Equipment Operator", "Oth adverse food reactions, not elsewhere classified, subs","€40,84"),
(1,"Landscaper", "Frostbite with tissue necrosis of thorax, initial encounter","€136,22"),
(1,"Terrazzo", "Disp fx of lateral condyle of r femr, 7thD","€146,70"),
(1,"Linemen", "Mood disorder due to known physiological condition","€146,17"),
(1,"Linemen", "Bipolar disorder, current episode mixed, mild","€108,25");